### ISSUE TITLE
预训练模型使用的训练集

### ISSUE THREAD

**Issue by EasternJournalist** [DQiaole/MemFlow#11]
您好！请问预训练模型是在这些数据集上分别训练的吗，有混合到一起训练的模型吗？或者请问哪个模型的域外泛化效果最好呢？

**Comment by DQiaole** [comment]
你好，things是指只用合成数据集训练；sintel在things的基础上加入了sintel、kitti、hd1k等数据集混合训练；spring和kitti则指得是最后再用对应的数据集微调。
一般的场景用sintel上的模型（MemFlowNet_sintel.pth）即可；自动驾驶场景可以用kitti模型。

**Comment by EasternJournalist** [comment]
神速回复啊。太好了，感谢！

**Comment by xy1565838851** [comment]
> 你好，things是指只用合成数据集训练；sintel在things的基础上加入了sintel、kitti、hd1k等数据集混合训练；spring和kitti则指得是最后再用对应的数据集微调。 一般的场景用sintel上的模型（MemFlowNet_sintel.pth）即可；自动驾驶场景可以用kitti模型。

好人一胎八个
