### ISSUE TITLE
no flash attention installed

### ISSUE THREAD

**Issue by ElseFaisal** [DQiaole/MemFlow#12]
Hi there!!

Thanks for releasing ur amazing work. When I was performing the inference, it outputs this message "no flash attention installed".

Is it handled by the code or should I installed it manually?

Thanks.
Faisal.

**Comment by DQiaole** [comment]
Hii, during inference, we use vanilla implementation of attention by default. So, you donot need to do anything.
However, if you want to speedup the inference process, you can install the flashattention and modify the inference code accordingly.

**Comment by ElseFaisal** [comment]
Also, is it possible to replace the feature extractor with my own network?

**Comment by DQiaole** [comment]
sure, we have tried two feature extractor in our paper (i.e., resnet and twins-encoder). but you need to re-train or finetune the model.

**Comment by ElseFaisal** [comment]
Is there any consideration I should take into account? such as the output dimensions of the last layer of the backbone, etc..

**Comment by DQiaole** [comment]
hi, we set the output diemnsion to 256 in our code. You can add an additional mlp layer to change the dimension to 256.

**Comment by DQiaole** [comment]
hi, we set the output diemnsion to 256 in our code. You can add an additional mlp layer to change the dimension to 256. And i donot think there is any other special consideration should be taken in account.

**Comment by ElseFaisal** [comment]
Thanks a lot

**Comment by DQiaole** [comment]
@s1ddok Hi, I have update the inference code with flash attn. Please check it.

**Comment by s1ddok** [comment]
@DQiaole thank you so much!!! I got 3x speed boost, extremely cool!
