### ISSUE TITLE
Access to code and models

### ISSUE THREAD

**Issue by zhou199604** [DQiaole/MemFlow#2]
Hello, I read the article "MemFlow: Optical Flow Estimation and Prediction with Memory", which has code and models available. Are these codes and models open?

**Comment by DQiaole** [comment]
Sure. I will clean and release the model and codes before the CVPR meeting. Maybe during late May or early June. Thanks for your attention.

**Comment by DQiaole** [comment]
We have released the codes and models. Thanks.
