### ISSUE TITLE
I noticed that there are several functions missing in the inference.py script. Are these necessary?

### ISSUE THREAD

**Issue by 1798857164** [DQiaole/MemFlow#5]
there are 'flow_viz', 'frame_utils', 'frame_utils', 'forward_interpolate'.

**Comment by DQiaole** [comment]
sure, they are necessary. you can find them under the ‘core/utils’ directory.发自我的 iPhone在 2024年7月7日，11:17，1798857164 ***@***.***> 写道：﻿
there are 'flow_viz', 'frame_utils', 'frame_utils', 'forward_interpolate'.

**Comment by 1798857164** [comment]
> 当然，这些是必要的。您可以在 'core/utils' 目录下找到它们。发布自我的 iPhone 在 2024 年 7 月 7 日，11:17，1798857164 ***@***.***> 写道：﻿有“flow_viz”，“frame_utils”，“frame_utils”，“forward_interpolate”。 —直接回复此电子邮件，在 GitHub 上查看或取消订阅。您收到此邮件是因为您订阅了此主题。消息 ID： ***@***.***>

thank you i got it！

**Comment by 1798857164** [comment]
> sure, they are necessary. you can find them under the ‘core/utils’ directory.发自我的 iPhone在 2024年7月7日，11:17，1798857164 ***@***.***> 写道：﻿ there are 'flow_viz', 'frame_utils', 'frame_utils', 'forward_interpolate'. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

By the way，I have another question. How to set the 'warm_start'? I have not found the key called 'warm_start' in things_memflownet.py.

**Comment by DQiaole** [comment]
hi, you can simply add a key 'warm_start' into the config file. And our `inference.py` will check the value of 'cfg.warm_start' as in 
https://github.com/DQiaole/MemFlow/blob/8338ff448aa010c1df86870b69ed139b68192c00/inference.py#L71-L72
